# Generated by Django 4.2.1 on 2023-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecdevolucion',
            field=models.DateField(null=True),
        ),
    ]
