# Generated by Django 4.2.1 on 2023-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_prestamo_fecdevolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
